development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gigpoint_for_musician_development
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gigpoint_for_musician_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gigpoint_for_musician_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
